version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

  backend:
    build: { context: ., dockerfile: backend/Dockerfile }
    environment:
      - ENV=dev
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: { redis: { condition: service_healthy } }
    ports: ["127.0.0.1:8001:8000"]
    command: ["python","-m","uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]

  worker:
    build: { context: ., dockerfile: worker/Dockerfile }
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: { redis: { condition: service_healthy } }
    command: ["celery","-A","app.celery_app","worker","-Q","vrillsy","--loglevel","INFO"]
